version: '3.3'

services:
  app-blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-blog
    container_name: app-blog
    ports:
      - "9000:8080"
    environment:
      DB_HOST: db-blog
      DB_PORT: 5432
      DB_DATABASE: homestead
      DB_USERNAME: root
      DB_PASSWORD: root
      FILESYSTEM_DRIVER: public
    networks:
      - blog-network
    depends_on:
      - db-blog
    volumes:
      - vendor:/var/www/vendor 
      - .:/var/www

  db-blog:
    image: postgres:latest
    container_name: db-blog
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=homestead
    volumes:
      - db-blog:/var/lib/mysql/
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  db-blog:
  vendor:
